name: 📦 Dependency update
description: Track a dependency upgrade and security triage
labels: [Dependencies]
body:
  - type: input
    id: dependency_name
    attributes:
      label: Dependency name
    validations:
      required: true

  - type: input
    id: from_to
    attributes:
      label: Current -> target version
      placeholder: "1.2.3 -> 1.2.4"
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why this update
      description: Include CVE links if security-driven.
    validations:
      required: true

  - type: dropdown
    id: risk
    attributes:
      label: Risk tier
      options:
        - T1
        - T2
        - T3
    validations:
      required: true

  - type: textarea
    id: verification
    attributes:
      label: Verification plan
      description: Tests/checks required before merge.
    validations:
      required: true

  - type: textarea
    id: rollback
    attributes:
      label: Rollback plan
    validations:
      required: true
