name: 🛠 Remediation Ticket
description: Standard ticket for remediation and tech debt work
labels: [Remediation, Lane C]
body:
  - type: input
    id: ticket_id
    attributes:
      label: Ticket ID
      description: e.g. R42
      placeholder: R___
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
    validations:
      required: true
  
  - type: textarea
    id: summary
    attributes:
      label: Summary / Objective
      description: Brief description of the problem and desired outcome.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria (DoR)
      description: |
        Checklist of what must be true for this ticket to be Done.
        - [ ] Implementation complete
        - [ ] Verification evidence attached
        - [ ] Rollback notes included (if P0/T3)
      value: |
        - [ ] Implementation complete for defined scope
        - [ ] Verification evidence attached in PR
        - [ ] Rollback notes included (if risky)
    validations:
      required: true

  - type: input
    id: dependencies
    attributes:
      label: Dependencies (DoR)
      description: List any blocking tickets or "None".
      placeholder: None
    validations:
      required: true

  - type: dropdown
    id: risk_tier
    attributes:
      label: Risk Tier (DoR)
      description: See Playbook for definitions. T3 requires additional verification.
      options:
        - T1 (Low)
        - T2 (Medium)
        - T3 (High)
    validations:
      required: true

  - type: textarea
    id: verification_plan
    attributes:
      label: Verification Plan (DoR)
      description: How will you verify this change? (Commands, manual steps)
    validations:
      required: true

  - type: checkboxes
    id: dor_checklist
    attributes:
      label: Definition of Ready (DoR) Check
      options:
        - label: I have confirmed the acceptance criteria are clear
          required: true
        - label: I strictly scoped this to one objective
          required: true
